name: 'Wait for Workflow Run'
description: 'Wait for all workflow_run workflows to be successful'
author: 'Marius Craciunoiu'

inputs:
  github-token:
    description: GitHub Token
    default: ${{ github.token }}

  sha:
    description: SHA to use (defaults to github.sha)
    default: ${{ github.sha }}

  timeout:
    description: timeout before we stop trying (in milliseconds) (defaults to 5 minutes)
    default: 300000

  delay:
    description: delay between status checks (in milliseconds)
    default: 5000

  cancelled-as-success:
    description: count cancelled runs as successful
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'
